#!/bin/bash

javac -XDignore.symbol.file src/main/java/com/xjeffrose/{log,xio}/*.java && \
java -ea                                             \
  -Xbootclasspath/p:src/main/java/com/xjeffrose/xio/ \
  $JAVA_OPTS                      \
  -Djava.net.preferIPv4Stack=true \
  -XX:+UseStringDeduplication     \
  -XX:-UseTLAB                    \
  -XX:+AggressiveOpts             \
  -XX:+UseParNewGC                \
  -XX:+UseConcMarkSweepGC         \
  -XX:+CMSParallelRemarkEnabled   \
  -XX:+CMSClassUnloadingEnabled   \
  -XX:ReservedCodeCacheSize=128m  \
  -XX:SurvivorRatio=128           \
  -XX:MaxTenuringThreshold=0      \
  -Xss8M                          \
  -Xms512M                        \
  -Xmx2G                          \
  -server                         \
  -cp src/main/java com.xjeffrose.xio.Main "$@" &&
echo 'Running xio on port 8080'
