<<: &common_steps
  steps:
    - run:
        name: update image
        command: apt-get update
    - run:
        name: install debian dependencies
        command: apt-get install -y openssl libssl-dev ca-certificates-java
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: ./gradlew :xio:dependencies
    - run:
        name: run build test verify
        command: ./gradlew :xio:build
    - run:
        name: build reports
        command: ./gradlew :xio:jacocoTestReport :xio:coveralls :xio:javadoc
    - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

<<: &pyunit_steps
  steps:
    - run:
        name: install python
        command: apt-get update && apt-get install -y python3 python3-pip libssl-dev libcurl4-openssl-dev
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-
    - run:
        name: install requirements
        command: pip3 install -r ./int-tests/requirements.txt
    - run:
        name: integration tests
        command: python3 ./int-tests/test_server.py

version: 2
jobs:
  build-jdk8:
    docker:
      - image: openjdk:8u171-jdk-stretch
    <<: *common_steps
  build-jdk9:
    docker:
      - image: openjdk:9.0-jdk-slim-sid
    <<: *common_steps
  build-jdk10:
    docker:
      - image: openjdk:10-jdk-slim
    <<: *common_steps
  int-test:
    docker:
      - image: openjdk:8u171-jdk-stretch
    <<: *pyunit_steps

workflows:
  version: 2
  build:
    jobs:
      - build-jdk8
#      - build-jdk9
#      - build-jdk10
      - int-test
