#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class HostnameRuleset:
  """
  Attributes:
   - blacklistHosts
   - whitelistHosts
  """

  thrift_spec = (
    None, # 0
    (1, TType.SET, 'blacklistHosts', (TType.STRING,None), None, ), # 1
    (2, TType.SET, 'whitelistHosts', (TType.STRING,None), None, ), # 2
  )

  def __init__(self, blacklistHosts=None, whitelistHosts=None,):
    self.blacklistHosts = blacklistHosts
    self.whitelistHosts = whitelistHosts

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.SET:
          self.blacklistHosts = set()
          (_etype3, _size0) = iprot.readSetBegin()
          for _i4 in xrange(_size0):
            _elem5 = iprot.readString()
            self.blacklistHosts.add(_elem5)
          iprot.readSetEnd()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.SET:
          self.whitelistHosts = set()
          (_etype9, _size6) = iprot.readSetBegin()
          for _i10 in xrange(_size6):
            _elem11 = iprot.readString()
            self.whitelistHosts.add(_elem11)
          iprot.readSetEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('HostnameRuleset')
    if self.blacklistHosts is not None:
      oprot.writeFieldBegin('blacklistHosts', TType.SET, 1)
      oprot.writeSetBegin(TType.STRING, len(self.blacklistHosts))
      for iter12 in self.blacklistHosts:
        oprot.writeString(iter12)
      oprot.writeSetEnd()
      oprot.writeFieldEnd()
    if self.whitelistHosts is not None:
      oprot.writeFieldBegin('whitelistHosts', TType.SET, 2)
      oprot.writeSetBegin(TType.STRING, len(self.whitelistHosts))
      for iter13 in self.whitelistHosts:
        oprot.writeString(iter13)
      oprot.writeSetEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.blacklistHosts is None:
      raise TProtocol.TProtocolException(message='Required field blacklistHosts is unset!')
    if self.whitelistHosts is None:
      raise TProtocol.TProtocolException(message='Required field whitelistHosts is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.blacklistHosts)
    value = (value * 31) ^ hash(self.whitelistHosts)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
