/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xjeffrose.xio.marshall.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Http1Method implements org.apache.thrift.TEnum {
  CONNECT(0),
  DELETE(1),
  GET(2),
  HEAD(3),
  OPTIONS(4),
  PATCH(5),
  POST(6),
  PUT(7),
  TRACE(8);

  private final int value;

  private Http1Method(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Http1Method findByValue(int value) { 
    switch (value) {
      case 0:
        return CONNECT;
      case 1:
        return DELETE;
      case 2:
        return GET;
      case 3:
        return HEAD;
      case 4:
        return OPTIONS;
      case 5:
        return PATCH;
      case 6:
        return POST;
      case 7:
        return PUT;
      case 8:
        return TRACE;
      default:
        return null;
    }
  }
}
