version: "2.1"

services:
  client:
    container_name: int-test-client
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      back:
        condition: service_healthy
      front:
        condition: service_healthy
#    stdin_open: true # docker-compose run client /bin/bash
#    tty: true
    command: ["python3", "/tests/proxy_load_tests.py"]
    links:
      - front
      - back

  back:
    build:
      context: ../int-test-backend-server
    environment:
      - JAVA_OPTS # just un-setting -DDEBUG
    ports:
      - "8444:443"
    healthcheck:
      test: ["CMD", "curl", "-m", "1", "-f", "-k", "https://localhost"]
      interval: 1s
      timeout: 3s
      retries: 10

  front:
    build:
      context: ../int-test-proxy-server
    environment:
      - JAVA_OPTS # just un-setting -DDEBUG
    links:
      - back
    ports:
      - "8443:443"
    healthcheck:
      test: ["CMD", "curl", "-m", "1", "-f", "-k", "https://localhost"]
      interval: 1s
      timeout: 3s
      retries: 10
