#!/bin/bash
#
# This script should install everything required to build the project.
# Currently geared towards OS X

brew install --HEAD paulp/extras/coursier
brew install infer
brew install drip
brew install javarepl
brew install pdex/core/jdep
brew install thrift
