#!/bin/bash
#
# This script should install everything required to build the project docs.
# Currently geared towards OS X

brew install python
cd docs
virtualenv .env
.env/bin/pip install sphinx javasphinx
