#!/usr/bin/env python

import sys

def pluckFileName(val):
  return val.split('java')[1]

def massageClassName(val):
  return val[1:-1].replace('/', '.')

print massageClassName(pluckFileName(sys.argv[1]))
