#!/usr/bin/env python

import sys

def pluckFileName(val):
  return val.split('java')[1]

def massageClassName(val):
  return val[1:-1].replace('/', '.')

def handle_args(args):
  return map(lambda x: massageClassName(pluckFileName(x)), args)

def main():
  print " ".join(handle_args(sys.argv[1:]))

if __name__ == '__main__':
  main()
