#!/usr/bin/env python

import argparse
import os

def generate_makefile():
  pass

def has_java_files(files):
  return any(map(lambda x: x.endswith('.java'), files))

def no_makefile(path):
  return not os.path.exists(os.path.join(path, 'Makefile'))

def parse_args():
  parser = argparse.ArgumentParser()
  parser.add_argument('src_dir', type=str)
  parser.add_argument('-n', '--dry-run', action='store_const', const=True, default=False)

  return parser.parse_args()

def main():
  args = parse_args()

  for path, dirs, files in os.walk(args.src_dir):
    if has_java_files(files) and no_makefile(path):
      if args.dry_run:
        print "{path} needs a Makefile".format(path=path)
      else:
        generate_makefile()

if __name__ == '__main__':
  main()
